version: "3"
services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        links:
            - elastic
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        env_file:
            - .env
        volumes:
            - newsbot_elastic:/usr/share/elasticsearch/data

volumes:
    newsbot_elastic: