version: "3"
services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        environment:
            - "discovery.type:single-node"
        env_file:
            - .env
        volumes:
            - newsbot_elastic:/usr/share/elasticsearch/data

volumes:
    newsbot_elastic: